### PR TITLE
Add trim to the form values

### PR DESCRIPTION
**Pull request by anpolimus**

### CODE REVIEW

**Comment by froboy** [comment]
Tested and looks great. Nice fix @anpolimus!

**Comment by anpolimus** [comment]
@podarok This is a quick fix to save our qa from pasting values with spaces during the testing.

**Comment by anpolimus** [comment]
If you are ok with it, can we do a small release

**Comment by podarok** [comment]
should we provide an update path? @anpolimus ( load config, save config ) @anpolimus

**Comment by anpolimus** [comment]
@podarok I'm not sure if we need to have an upgrade path here.
All clients that have this module installed are using it properly. This is just to save time during regression testing.

**Comment by podarok** [comment]
tagged @anpolimus https://github.com/ymcatwincities/daxko_sso/releases/tag/1.2

**Comment by anpolimus** [comment]
@podarok , thank you

**Pull request merged**
